/* eslint-disable no-unused-vars */
import console from "node:console";
import { URL } from "node:url";
import process from "node:process";
import { readFileSync } from "node:fs";
import { build } from "esbuild";

// Commented out because this package doesn't currently have any dependencies
// const { dependencies } = JSON.parse(readFileSync(new URL("./package.json", import.meta.url)));
const production = process.argv[2] === "--production";

const wrapper = (name, config) => {
    return build({
        bundle: true,
        // Commented out because this package doesn't currently have any dependencies
        // The browser build shouldn't utilize any code that depends on these
        // external: Object.keys(dependencies),
        watch: production ? false : {
            onRebuild(error, result) {
                if (error) {
                    console.error(`[watch] building ${name} failed:`, error);
                } else {
                    const { stop, ...alerts } = result;
                    console.log(`[watch] built ${name}:`, alerts);
                }
            },
        },
        target: "es2020",
        banner: {
            js: "/* This is a bundled file generated by esbuild\nIf you want to view the source, please visit the github repository */",
        },
        ...config,
    }).then((result) => {
        const { stop, ...alerts } = result;
        console.log(`built ${name}:`, alerts);
    }).catch((error) => {
        console.error(`building ${name} failed:`, error);
        process.exit(1);
    });
};

const builds = [
    wrapper("minified browser esm", {
        entryPoints: ["./src/index.browser.js"],
        minify: true,
        format: "esm",
        platform: "browser",
        outfile: "./dist/index.browser.min.js",
    }),
    wrapper("node cjs", {
        entryPoints: ["./src/index.commonjs.js"],
        format: "cjs",
        platform: "node",
        outfile: "./dist/index.cjs",
    }),
];

if (!production) {
    Promise.all(builds).then(() => {
        console.log("watch mode enabled...");
    });
}
