/* eslint-disable no-unused-vars */
import console from "node:console";
import { exit } from "node:process";
import { readFileSync } from "node:fs";
import { URL } from "node:url";
import { build as esbuild } from "esbuild";

const { dependencies } = JSON.parse(readFileSync(new URL("./package.json", import.meta.url)));

/** Helper function for multiple builds */
const build = async function(name, options) {
    try {
        const { outputFiles, metafile, mangleCache, ...buildResult } = await esbuild({
            bundle: true,
            minify: true,
            target: "es2020",
            external: Object.keys(dependencies),
            banner: {
                js: "/* This is a bundled file generated by esbuild\nIf you want to view the source, please visit the github repository */",
            },
            ...options,
        });
        console.log(`built ${name}:`, buildResult);
    } catch (error) {
        console.error(`building ${name} failed:`, error);
        exit(1);
    }
};

(async function() {
    await build("minified browser esm", {
        entryPoints: ["./src/index.browser.js"],
        format: "esm",
        platform: "browser",
        outfile: "./dist/index.browser.js",
    });
    await build("minified node cjs", {
        entryPoints: ["./src/index.cjs.js"],
        format: "cjs",
        platform: "node",
        outfile: "./dist/index.cjs",
    });
})();
